apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-crud-api
  namespace: master
spec:
  selector:
    matchLabels:
      app: student-crud-api
  template:
    metadata:
      labels:
        app: student-crud-api
    spec:
      containers:
      - name: student-crud-api
        image: akshay754/student_crud_api:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 500
